export {MenuContentPage} from "./menu-content.page"
export {ProductsListPage} from "./products-list.page"
export {ShopingCartPage} from "./shoping-cart.page"
export {LoginPage} from "./login.page"
export {AddressStepPage} from "./address-step.page"
export {ShippingStepPage} from "./shipping-step.page"
